modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "LGPL3"

[[mods]]
modId = "sleepingoverhaul"
version = "${version}"
displayName = "SleepingOverhaul"
authors = "CosmicDan"
description = '''
Replaces skip-to-day on sleep with a beautiful panoramic timelapse, and more!
'''
logoFile = "logo.png"
displayURL = "https://github.com/CosmicDan-Minecraft/SleepingOverhaul2/"

[[dependencies.sleepingoverhaul]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sleepingoverhaul]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sleepingoverhaul]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering = "NONE"
side = "BOTH"